[project]
name = "scene-graph-project"
version = "0.1.0"
description = "Scene graph rule mining utilities"
requires-python = ">=3.8"
dependencies = [
	"jinja2",
	"typeguard",
	"PyClause @ git+https://github.com/symbolic-kg/PyClause.git",
	"visual_genome @ git+https://github.com/ranjaykrishna/visual_genome_python_driver.git",
	"networkx",
	"tqdm",
	"maturin",
	"scallopy @ git+https://github.com/scallop-lang/scallop.git#egg=scallopy&subdirectory=etc/scallopy",
]

[tool.setuptools.packages.find]
include = ["rule_mining*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
