#https://web.informatik.uni-mannheim.de/AnyBURL/2019-05/params.html
PATH_TRAINING = /home/sebastian/Documents/scene_graph_project/rule_mining/datasets/visual_genome/relationships.triplet.txt
PATH_OUTPUT   = rules

SNAPSHOTS_AT = 10,50,100

WORKER_THREADS = 7

# #1 for greedy or 2 for weighted
# POLICY = 2
# #Possible values are 1 (correct predictions), 3 (correct predictions weighted by confidence with laplace smoothing), 5 (correct predictions weighted by confidence with laplace smoothing divided by (rule length-1)^2). 
# REWARD = 5
# #0.1 is the default setting, which allocates a core with a probability of 0.1 randomly. You can change this to a value of 0.0 to 1.0 (= random policy).
# EPSILON = 0.1
# #Thresholds for learning rules
# THRESHOLD_CORRECT_PREDICTIONS = 2
# #Thresholds for learning rules
# THRESHOLD_CONFIDENCE = 0.0001
# #called binary rules or cyclic rules
# MAX_LENGTH_CYCLIC = 3
# #rules that try to capture very simple relation specific frequencies
# ZERO_RULES_ACTIVE = false
# #these rules are called AC1 and AC2 rule or U_c or U_d rules (unary)
# MAX_LENGTH_ACYCLIC = 1
# #U_d or AC1 rules that are derived from a closed path
# MAX_LENGTH_GROUNDED_CYCLIC = 1
# #change if dealing with really large scene graphs
# THRESHOLD_CORRECT_PREDICTIONS = 5

# #SINGLE_RELATIONS = relation1,relation2,relation3 #? use to specify when a single or multiple specific relations are desired rather than all of them.

