#https://web.informatik.uni-mannheim.de/AnyBURL/2019-05/params.html
PATH_TRAINING = /home/sebastian/Documents/scene_graph_project/rule_mining/datasets/mini_sets/FB15/train.txt
PATH_VALID    = /home/sebastian/Documents/scene_graph_project/rule_mining/datasets/mini_sets/FB15/valid.txt
PATH_TEST     = /home/sebastian/Documents/scene_graph_project/rule_mining/datasets/mini_sets/FB15/test.txt


PATH_PREDICTIONS = predictions/preds-100

TOP_K = 100
